### ISSUE TITLE
Document the right way to test out new additions to the registry

### ISSUE THREAD

**Issue by vincecima** [lvillani/just-install#101]
The instructions for testing new entries to the registry are unclear. Perhaps a command line parameter to point to a custom registry file would work well?

**Comment by vincecima** [comment]
Just to follow it up, I used Windows search to find the local copy of the registry file. I then copied and pasted my potential additions into that file.

**Comment by lvillani** [comment]
`just-install` tries to load a file called `just-install.json` from the current working directory, if there. Trying the "canonical" path otherwise (and downloading it there, if necessary). But you're right, this needs to be documented.

**Comment by vincecima** [comment]
@lvillani I was thinking about hacking in a new command line flag. Flag would point to another registry file that would be both _additive_ and _overriding_. That way the development scenario would be more straight forward and folks who want to maintain a custom registry file for whatever reason can use it too. Thoughts?

**Comment by lvillani** [comment]
That would be nice. I have a clear idea how this can be implemented in a clean and generic way. I'm on a business trip at the moment but I'll see what I can do when I get back home.

**Comment by lvillani** [comment]
On second thought, I don't really have the time to implement said feature and will just add a blurb to CONTRIBUTING.md
