### ISSUE TITLE
Document how to figure out which type of installer a file is

### ISSUE THREAD

**Issue by vincecima** [lvillani/just-install#104]
Tools like http://www.softpedia.com/get/System/Launchers-Shutdown-Tools/Universal-Silent-Switch-Finder.shtml might be helpful. Perhaps we can build it into the just-install exe?

**Comment by lvillani** [comment]
Building USSF into just-install is out of the question. Visual inspection and running the installer once is enough 9 times ouf of 10. USSF seems to not be maintained anymore.

Really, there's nothing I can offer besides "try to run installers enough times that you are able to recognize them, or contact the vendor if anything else fails".
