### ISSUE TITLE
Clarification: Support for un-silent packages

### ISSUE THREAD

**Issue by vincecima** [lvillani/just-install#119]
Currently, just-install handles packages that can't be made silent (iTunes for example) just fine. Some questions:

1. Should these packages be flagged somehow in the registry file?
1. If yes to the above, should the user be forced to pass a command line flag agreeing to their use. If the flag isn't passed, do we error out and alert why?

**Comment by lvillani** [comment]
Flagging the package and showing a warning would be nice but I would not force users to pass a special command line flag in order to install them.

**Comment by vincecima** [comment]
:+1:

**Comment by lvillani** [comment]
By the way, I was wondering that maybe we can just show a warning for any package that has `kind` set to `as-is`.
