### ISSUE TITLE
Feature Request: Support standalone applications

### ISSUE THREAD

**Issue by vincecima** [lvillani/just-install#122]
Applications like https://rg3.github.io/youtube-dl/download.html are distributed as a standalone .exe. They just need to be copied somewhere and a shim added to the user's default PATH. `just-install` already supports this if the file is a .zip, it just needs to be extended to .exe.

**Comment by lvillani** [comment]
:+1:

**Comment by lvillani** [comment]
Btw you can now install beta versions by running `msiexec /i http://beta.just-install.it`. These get built after every commit on master.

**Comment by lvillani** [comment]
Also note that the "destination" field is expected to be a full directory + file name for "copy" entries (whereas with "zip" entry we expect it to be a directory name).
