### ISSUE TITLE
Add "clean" command to remove all temporary files

### ISSUE THREAD

**Issue by lvillani** [lvillani/just-install#127]
This should remove the whole just-install directory under `%TEMP%`, removing both the cached registry file and any installer that has been downloaded before.

**Comment by guiweber** [comment]
The clean command doesn't seem to be run after an install routine. The folder and its content remain there.

By the way, this may be a good thing for development, when testing new catalog entries (you don't want to have to update every time), but maybe it could be toggled through the command line?

**Comment by lvillani** [comment]
That command is meant to be run explicitly by the user (it works in a manner similar to `apt-get`). Stuff in `%TEMP%` may be cleaned up automatically by the system anyway..
