### ISSUE TITLE
Readme points the the website for list of available packages, but it doesn't exist

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#132]
The readme says :

> To see the list of available packages head over to http://just-install.it.

As far as I can see, there is no list on the website. Is this something you plan on doing or should the readme be updated?

I think this list is something that would be nice to have to entice people to try just-install. If it's something that won't be done soon, I feel it would be better remove the link instead of directing people to something that isn't there (as a new user I did check the website several times to make sure the list wasn't hidden somewhere).

**Comment by lvillani** [comment]
The list is definitely there (tested on iOS, Android, Windows, Ubuntu, OS X, with their respective default browsers).
![screenshot 2016-03-28 10 22 14](https://cloud.githubusercontent.com/assets/241660/14074167/4b860a50-f4cf-11e5-91e1-e9a073c0182c.png)

**Comment by guiweber** [comment]
Ok, I just confirmed that it does appear when using Internet Explorer but doesn't when using Firefox.

Firefox gives this security error in the console, which is most likely the source of the issue:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://rawgit.com/lvillani/just-install/master/just-install.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by lvillani** [comment]
That's weird, the screenshot above is from Firefox on OS X. I also tried Firefox on Android and I still can see the list.

**Comment by guiweber** [comment]
I narrowed down the issue to a compatibility problem with the [HTTPS Everywhere](https://www.eff.org/https-everywhere) add-on. It's the first time I see this kind of issue with it and it's kind of weird wince it's says it has been blocked as a cross-origin request

I'll open a ticket on their github to see what they think about this behavior.

**Comment by lvillani** [comment]
:+1: I'm closing this issue, then.
