### ISSUE TITLE
Downloads without the proper extension in the URL don't install

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#141]
I tried adding VeraCrypt to the catalog. The file is downloaded by just-install, but it is missing its file extension (.exe), so J-I says "The file does not exist" when it tries installing it. The file downloaded file works fine outside of J-I if you add the extension manually.

The URL lacks a file name altogether, but if you put it in a web browser, the file will be downloaded with the proper name and extension.
`https://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=veracrypt&DownloadId=1537178&FileTime=130999181356070000&Build=21031`

Here is the download page for reference:
https://veracrypt.codeplex.com/wikipage?title=Downloads

**Comment by guiweber** [comment]
Ok, so I found issue #50 and figured out how I could make it work. Still, it would be nice to document the various options in registry.md!

**Comment by lvillani** [comment]
Yep, good catch! I'm adding that to the document.
