### ISSUE TITLE
Two issues with the virtual box extension pack

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#142]
I'm trying to add the Virtual Box extension pack to the catalog, but there are two issues.

First, just-install tells me that it's not a valid win32 application. This is most likely due to the file extension which is `.vbox-extpack`. I was able to launch the installer manually from the console, so it can work.

Second, the installer will give an error and abort if the filename is not the original filename. Even though I didn't get to that point in Just Install, I anticipate this will be an issue since Just-Install changes the filenames when downloading.

Here is the link to the file for referene: http://download.virtualbox.org/virtualbox/5.0.16/Oracle_VM_VirtualBox_Extension_Pack-5.0.16-105871.vbox-extpack

**Comment by lvillani** [comment]
Btw, to try this one you can install the beta version of just-install (that gets automatically rebuilt after each commit on the `master` branch) by running `msiexec /i http://beta.just-install.it`

**Comment by guiweber** [comment]
Good to know, thanks!
