### ISSUE TITLE
Feature request: Add parameter to change Temp folder

### ISSUE THREAD

**Issue by pierre-guillot** [lvillani/just-install#147]
I want to use just-install to download the lastet installer of many app. Thus I use the --download-only option on my commande.
But installers are in the %temp% folder and you cannot change it.
Please add a --dir option to choose the temp folder.

**Comment by lvillani** [comment]
In the end I decided to not implement this feature. I'm sorry. To work-around: download packages using `--download-only` and then copy/move `%TEMP%/just-install`.
