### ISSUE TITLE
Keeping the registry up-to-date

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#151]
As you might have noticed in PR  #150, I started working on an script to help keep the registry up-to-date: https://github.com/guiweber/just-install-updater

I feel that keeping it up-to-date is key to the usefulness of just-install, and that updating manually is too time consuming to be a sustainable solution.

If you like the idea, it would be good to add something to the contribution guidelines so that people consider adding an update rule to the updater when they add an app to the registry.

So please let me know what you think. I would have a few other requests to help streamline the process, if you're open to it.

**Comment by lvillani** [comment]
That's an excellent idea and I like the way update-rules.json is structured and works. I'd like to have something like this in my repo, but I'd probably rewrite it in go (since go by itself is enough of a nuisance to set-up for development, I wouldn't want to add even node to the mix), so I'm perfectly fine if you run it from time to time and submit a pull request :smile:

**Comment by guiweber** [comment]
Makes sense.

In the meantime, would you be open to making a few changes that would make the update process easier? I have two main issues at the moment:

1. Testing the updated urls locally in just-install is long. I could test them in node but then I wouldn't be 100% sure something won't go wrong in just-install. For now I need to navigate to `just-install -d [packages]`, let the packages download, then check the results manually, and finally do `just-install clean`. What would be great would be to have a 'test' command that could be called for a specific package. It would need to...

  - always use the local registry file
  - not download the file but just checks the status code and content type
  - not require admin privileges
  - exit with 0 on success and 1 on failure. 

  That way, I can automatically launch just-install in test mode from node for each package that is updated and check the exit code to see if it worked or not. I see you already have something to that effect in registry_test.go - could it be integrated into just-install itself?

2. The download links that are easy to get on some sites (mainly Fosshub and Sourceforge) have an expiry timer. I have some ideas how this could be bypassed, but it would require some new capabilities in just-install.

**Comment by lvillani** [comment]
Re 1: The current test suite already does what you are asking. There are no plans to integrate that into just-install itself.

Re 2: I don't know Fosshub but Sourceforge provides permanent download links (like those that are currently being used)
