### ISSUE TITLE
Testing: log URLs that are being tested

### ISSUE THREAD

**Issue by lvillani** [lvillani/just-install#160]
Also make sure to print them in Travis logs

**Comment by guiweber** [comment]
Would it be possible to print a summary of the errors at the end? Or make the errors appear in red? With the large number of URLs now printed in the test log, I find it harder than before to see what went wrong when a build fails.

**Comment by lvillani** [comment]
@guiweber Is it better with the latest changes?

**Comment by guiweber** [comment]
Yes, it's perfect like it is now. Thanks.
