### ISSUE TITLE
Testing: automatically retry failed request

### ISSUE THREAD

**Issue by lvillani** [lvillani/just-install#161]
Up to 3 times, with a 30 seconds delay. This should reduce false negatives while running Travis tests.

Also make sure to log failed requests for further inspection.

**Comment by guiweber** [comment]
I had some builds failing because the test timed out on a good download link. Some hosts (such as sourceforge) add a delay before the download starts, so a longer timeout may also help with those.

**Comment by lvillani** [comment]
Done in 072242cfffba6fa62b855e1f6ad92382fcee9dff
