### ISSUE TITLE
Consider removing obsolete apps

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#163]
In order to keep the registry clean and easier to maintain, I suggest removing everything related to python 2.6 (python26, python26-pip, python26-win32). Python 2.7 didn't break compatibility with 2.6, so I don't see why people would still be running 2.6 six years after 2.7 was released. I suggest consolidating everything related to the 2.x branch under the *python2* label, so we'll have the latest 2.x versions under *python2* and the latest 3.x version under *python3*.

I also suggest removing everything replacing all year specific apps (sqlserver-express-2008, visualcpp-express-2008, qt-vs2008) with a year-free label offering the latest version. It seems to me that keeping year-free labels that always point to the latest version more closely matches the goal of just-install to keep things simple and not bother the user. Having to check what year specific versions are available and update them in your install script seems to go against that.

Let  me know if you're ok with that, and I can take care of the changes.

**Comment by lvillani** [comment]
We need to keep Python 2.6 because one of our clients still uses it and we need to install it on our CI workers. Same goes for Visual Studio 2008 and Qt, we need those exact versions to build PyQt from sources.

**Comment by vincecima** [comment]
@lvillani can you elaborate on the relationship between `just-install` and your clients needs?

**Comment by lvillani** [comment]
@vincecima I started just-install while working at my current company to automate installation of some development tools on our Jenkins/BuildBot workers, mainly because I was dissatisfied with all the alternatives. Some of the stuff in the catalog is there to support my company's needs.

**Comment by vincecima** [comment]
Thanks @lvillani. Good to know who else the project is serving. Thanks to you and your company for open sourcing all this great work.

**Comment by guiweber** [comment]
@lvillani Thanks for the explanation. It would be nice to have a way of identifying those "legacy" packages in the registry. This would not only tell us, humans, to leave them alone but also allow us to ignore them programmatically (e.g. in the updater code).

Short of suggesting a versioning system, here are some simple ideas: 

- Use the version field: since those packages are version specific and contain the version number in their name, the version field could be set to a special identifier (for example, the updater is already ignoring the packages that have "latest" in their version field.)
- Add an optional "legacy" field, set to true only for legacy packages
