### ISSUE TITLE
Adding catalog items

### ISSUE THREAD

**Issue by davidpaige** [lvillani/just-install#164]
I've read the manual, but I'm not sure how to add programs to the catalog.  I don't have a catalog.yml file on my system.  Is that something that I create (and where?), or is it something that you create?

I would like to get smplayer.exe added, but I don't know how.

**Comment by guiweber** [comment]
New catalog entries need to be added to [just-install.json](../blob/master/just-install.json)

Reading [the contribution guidelines](../blob/master/CONTRIBUTING.md) as well as [the registry (catalog) documentation](../blob/master/doc/registry.md) should help you get started.

**Comment by lvillani** [comment]
Closing this for now.
