### ISSUE TITLE
Feature request: remove and upgrade pkg features needed.

### ISSUE THREAD

**Issue by marxwang** [lvillani/just-install#165]
Just-install is cool and easy-to-use.
I use chocolate w/wo GUI, but it always slow.
if upgrade pkg and remove pkg features could be fulfilled, it would be more useful. 
Thanks *lvillani* for the good tool !

**Comment by lvillani** [comment]
Package removal and upgrades are outside the scope of this project. See the [rationale](http://lorenzo.villani.me/2013/04/08/just-install-my-stuff/).
