### ISSUE TITLE
Consider include style package definitions

### ISSUE THREAD

**Issue by maphew** [lvillani/just-install#174]
Please consider using an "include style" method of package definitions instead of the current everything in one master file method. Sooner or later the master file will get just too big to manage easily. (At the very least it means contributors won't have to think about properly alphabetizing contributions ;-)

Master `just-install.json`:

```
{
    "package-dir": {
        "D:\\apps\\just-install\\packages"
    }
}
```
Individual packages:

```
...\just-install\packages\everything-search.json
...\just-install\packages\enpass.json
...\just-install\packages\exeproxy.json
...etc
```
Where each single file looks like:

    {
    "everything-search": {
      "installer": {
        "kind": "nsis",
        "x86": "http://www.voidtools.com/Everything-{{.version}}.x86-Setup.exe"
      },
      "version": "1.3.4.686"
    },

A natural flexible extension of this basic structure could mean multiple sources with little extra work, e.g. official just-install source plus a personal collection:

```
{
    "package-dir": {
        "D:\\apps\\just-install.it\\packages",
        "X:\\internal\packages",
    }
}
```

**Comment by lvillani** [comment]
Sorry but that's not a feature I'm going to implement since I deem it makes just-install a little more complex for a very small gain. As for alphabetising entries in `just-install.json`, well I can (and do) run `jsonlint` on that file from time to time to "fix" it anyway 😉

**Comment by maphew** [comment]
you da boss. :) Thanks for tip about jsonlint, that's useful.

**Comment by maphew** [comment]
how do you get jsonlint to alphabetize? jsonlint.com and http://zaa.ch/jsonlint/ seem to correct indentation etc. but aren't changing order for me.

![2016-07-19 16_21_49-jsonlint - the json validator](https://cloud.githubusercontent.com/assets/486200/16969880/03357658-4dcd-11e6-8d49-640e688e55f7.png)
