### ISSUE TITLE
Libre office breaking the build

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#182]
Although the build gives an error about the content type, downloading the app in just-install still works. The download link itself hasn't changed.

registry_test.go:77: libreoffice (x86_64): http://download.documentfoundation.org/libreoffice/stable/5.1.4/win/x86_64/LibreOffice_5.1.4_Win_x64.msi, **The content type was application/x-troff-man**

**Comment by lvillani** [comment]
I think it's one of their mirrors that's sending the wrong `Content-Type` for the `.msi` file. The one I'm testing locally works just fine.
