### ISSUE TITLE
Shims not created, no error to work with

### ISSUE THREAD

**Issue by maphew** [lvillani/just-install#192]
I'm not getting shims created for this application I'm preparing for adding to the master list:
31320004f0e917644b16949b81074557f5fa01b8

The application (image magick) installs and works from Start Menu There is no error message reported, but no files are created in C:\Shims. I'm not sure if I made an error in the json file or if shims is broken or...
`exeproxy` is in PATH.

```
C:\Shims>just-install image-magick-16
2016/07/20 13:47:48 x86_64 - http://www.imagemagick.org/download/binaries/ImageM
agick-7.0.2-4-Q16-x86-dll.exe
22.80 MB / 22.80 MB [===================================] 100.00 % 7.88 MB/s 2s
2016/07/20 13:47:51 Running C:\Users\mhwilkie\AppData\Local\Temp\just-install\EE
9C8EE9.exe /norestart /sp- /verysilent

C:\Shims>dir
 Volume in drive C has no label.
 Volume Serial Number is F213-D8F7

 Directory of C:\Shims

2016-07-08  09:29 AM    <DIR>          .
2016-07-08  09:29 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  29,455,003,648 bytes free

C:\Shims>exeproxy /?
Cannot load the target executable path from the resource
```

**Comment by maphew** [comment]
```
C:\Shims>just-install --shim image-magick-16

C:\Shims>dir
 Volume in drive C has no label.
 Volume Serial Number is F213-D8F7

 Directory of C:\Shims

2016-07-08  09:29 AM    <DIR>          .
2016-07-08  09:29 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  29,420,171,264 bytes free

C:\Shims>dir /s/b c:\magick.exe
c:\Program Files (x86)\ImageMagick-7.0.2-Q16\magick.exe

C:\Shims>
```

**Comment by maphew** [comment]
exeproxy works manually (though I had quite a time figuring out the proper syntax):

```
C:\Shims>exeproxy exeproxy-copy test.exe "c:\Program Files (x86)\ImageMagick-7.0
.2-Q16\magick.exe"

C:\Shims>dir
 Volume in drive C has no label.
 Volume Serial Number is F213-D8F7

 Directory of C:\Shims

2016-07-20  02:39 PM    <DIR>          .
2016-07-20  02:39 PM    <DIR>          ..
2016-07-20  02:39 PM            16,384 test.exe
               1 File(s)         16,384 bytes
               2 Dir(s)  29,388,083,200 bytes free

C:\Shims>test
Error: Invalid argument or not enough arguments

Usage: magick.exe [ {option} | {image} ... ] {output_image}
       magick.exe [ {option} | {image} ... ] -script {filename} [ {script_args}
...]
       magick.exe -help | -version | -usage | -list {option}
```

**Comment by lvillani** [comment]
That's weird. Can you post here the full path to exeproxy's executable?

**Comment by maphew** [comment]
`C:\bin\exeproxy.exe`, and bin is in PATH, `PATH=C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\bin;C:\apps\SysInternals;C:\ProgramData\Oracle\Java\javapath;C:\local\oracle\win64\instantclient_12_1;C:\local\oracle\win32\instantclient_12_1;C:\Program Files\TortoiseHg\`

**Comment by lvillani** [comment]
That's not the correct path. just-install expects exeproxy to be installed where it would install it: see [here](https://github.com/lvillani/just-install/blob/6b2ab8900e39a33ef3934a501093ed7bc106cb1a/registry.go#L314). Please reinstall exeproxy with just-install itself (`just-install exeproxy`).

**Comment by lvillani** [comment]
Did you manage to get shims working after my last comment?

**Comment by lvillani** [comment]
Closing due to lack of updates. Feel free to re-open if necessary.

**Comment by maphew** [comment]
Sorry for long silence: yes, after installing exeproxy with just-install it works correctly.
