### ISSUE TITLE
Build fails on JRE link

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#193]
The content type is not recognized by the test suite, but the download link works just fine in just-install.

http://javadl.oracle.com/webapps/download/AutoDL?BundleId=211997, **The content type was application/x-sdlc**

**Comment by lvillani** [comment]
I'm adding the new MIME type to the list of accepted ones.

**Comment by lvillani** [comment]
Fixed by 8a6f6921e71ea076c94930822e9fe072061a7112
