### ISSUE TITLE
Proposal : Speedfan and Adobe Reader

### ISSUE THREAD

**Issue by pierre-guillot** [lvillani/just-install#200]
Hello,
Here is a proposal software to add in just-install : SpeedFan (monitors voltages, fan speeds and temperatures in computers) : 

```
"Speedfan": {
      "installer": {
        "kind": "exe",
        "x86": "http://www.almico.com/speedfan452.exe",
      },
      "version": "4.52"
},
```
For adobe reader, I think it's more complicated because you need two packets : base install (version 11) and update (version 11.0.17). Update file is not a exe or msi file. And link to download there files are in ftp://. Another problem with version 11 is you not have a Multi-Language install.
Plus, you can use the DC version instade of 11 on windows 7 or more. 

```
"Adobe-reader-11": {
      "installer": {
        "kind": "msi",
        "x86": "ftp://ftp.adobe.com/pub/adobe/reader/win/11.x/11.0.00/en_US/AdbeRdr11000_en_US.msi",
      },
      "version": "11.00"
},
"Adobe-reader-11-update": {
      "installer": {
        "kind": "msp",
        "x86": "ftp://ftp.adobe.com/pub/adobe/reader/win/11.x/11.0.17/misc/AdbeRdrUpd11017_MUI.msp",
      },
      "version": "11.017"
},


"Adobe-reader-DC": {
      "installer": {
        "kind": "exe",
        "x86": "ftp://ftp.adobe.com/pub/adobe/reader/win/AcrobatDC/1500720033/AcroRdrDC1500720033_MUI.exe",
      },
      "version": "15.00720033"
},
"Adobe-reader-DC-update": {
      "installer": {
        "kind": "msp",
        "x86": "ftp://ftp.adobe.com/pub/adobe/reader/win/AcrobatDC/1501720053/AcroRdrDCUpd1501720053_MUI.msp",
      },
      "version": "11.01720053"
},
```
I'm sorry in advance if my json code is not good.

**Comment by lvillani** [comment]
Please open a pull request for Speedfan.

Adobe Reader is also available over http/https, no need to use FTP (and I have no plans to add support for it for the foreseeable future). Also, there's no need to have separate entries for update packages. It is responsibility of the developer to add a self-update mechanism to its software.
