### ISSUE TITLE
Support for classic shell

### ISSUE THREAD

**Issue by pthivierge** [lvillani/just-install#204]
Hello, 

I was wondering if it could be possible to get support for classic shell.
The installer commands seems straingforward:
http://www.classicshell.net/faq/#install_commands

download link: http://www.mediafire.com/download/dbbil746gavpirr/ClassicShellSetup_4_3_0.exe

thanks for your attention :)

**Comment by lvillani** [comment]
It should be possible, I'll try to get around doing it ASAP. The only thing that worries me is the mediafire link since they usually prevent hot-linking.

P.S.: It's weird to see software distributed that way.

**Comment by pthivierge** [comment]
Thanks for the update! I'll stay tuned for sure.  I really like what you did. I may have few more ideas but before I'll need to start looking into your code-base. :)

I succeeded to install it this way using Powershell to download. 
```
cmd.exe /c powershell -Command "wget http://www.mediafire.com/download/dbbil746gavpirr/ClassicShellSetup_4_3_0.exe -UseBasicParsing -OutFile $env:TEMP\csSetup.exe"

cmd.exe /c powershell -Command "& $env:TEMP\csSetup.exe /qn"
```
