### ISSUE TITLE
Steam MSI not reacheable

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#206]
It looks like steam doesn't have an MSI installer anymore. The installer on their website is an EXE and I couldn't find anything else.

Did you get the download link from somewhere else when you added it to the registry? I just want to make sure I'm not overlooking something before changing the installer type.

**Comment by lvillani** [comment]
I think I used the installer provided on the home page or the first result
for "Steam MSI installer" that looked legit. Feel free to update the entry
with whatever they are providing now. Even though the lack of an MSI
installer would be a bummer.

**Comment by lvillani** [comment]
I'm going to fix this myself since I recently reinstalled Windows and I need to install Steam on this machine.
