### ISSUE TITLE
Allow automatically installing programs with just-install.exe

### ISSUE THREAD

**Issue by geek1011** [lvillani/just-install#207]
I usually use Ninite to install my apps, but then I decided to switch to this.

I like the feature of Ninite where I can have an EXE which will automatically install applications. 

Would it be possible to use [PE Overlays](http://reverseengineering.stackexchange.com/questions/2014/how-can-one-extract-the-appended-data-of-a-portable-executable) to have a just-install executable which automatically installs applications. 

I would be willing to help with the development of this feature.
**EDIT:** I have put my implementation of this feature in the 3rd comment
**FINAL EDIT**: I have put a fully working, non hackish, and stable implementation and submitted a PR

**Comment by geek1011** [comment]
See https://golang.org/pkg/debug/pe/ and http://reverseengineering.stackexchange.com/questions/2014/how-can-one-extract-the-appended-data-of-a-portable-executable

**Comment by geek1011** [comment]
The way I am suggesting is:

In just-install.go, change os.Run(os.args) to an if statement which checks for text in the PE overlay. If there is not text, just run the usual stuff. If there is text, use it as the arguments instead. 

The hardest part would be the code to extract the PE overlay.

**Comment by geek1011** [comment]
Also, if this feature is implemented, I am willing to create a web-based interface (it will require a modern browser) which will work like Ninite. I would do this with XMLHTTPRequest to get `just-install.exe`, read it as a blob, create another blob with the arguments, append them to each other, and then create a link with the url of the final blob for the user to download.

**Comment by geek1011** [comment]
Something like this would go in just-install.go

https://play.golang.org/p/_jQFZT7Lha

````go
package main

import (
	"fmt"
	"strings"
)

func main() {
	marker := "!STARTARGS!"
	
	// For testing
	ownbinary := "asdadnnd08j32o4ik2m3n4r9jerfs!STasdiaosmmda!STARTARGS!firefox git"
	
	// Actual:
	// Add code to read own executable as a string here
	
	s := strings.SplitN(ownbinary, marker, 2)
	
	if len(s) == 2 {
		// For testing
		fmt.Println("Using args: " + s[1])
		
		// Actual: 
		// app.Run(s[1])
	} else {
		// For testing
		fmt.Println("Continue with normal args")
		
		// Actual:
		// app.Run(os.args)
	}
}

````

**Comment by geek1011** [comment]
I have got the code figured out. It is kind of hackish, but it works. I have tested it quite a bit.

All you need to do is replace `app.Run(os.Args)` with the following code. First, the code will read in it's own executable as a string, then it will get everything after the last occurrence of `!STARTARGS!`. This is how it finds the start of the PE Overlay. If there is nothing after the last occurrence, then the app will continue on normally. If any errors occur, the code will continue normally the way it would without my change.

The reason why it is hackish is because when the code is compiled, all the text variables will appear in the executable as plain text. The way this makes sure that that is not interpreted as the arguments is it splits `!STARTARGS!` into two parts which are in separate parts of the code, and then makes sure there is nothing in between the two parts. Even though this is kind of hackish, it should not cause any side effects.occurence

````go
	CommandPath := func() (name string, err error) {
		name = os.Args[0]

		if name[0] == '.' {
			name, err = filepath.Abs(name)
			if err == nil {
				name = filepath.Clean(name)
			}
		} else {
			name, err = exec.LookPath(filepath.Clean(name))
		}
		return
	}

	pathname, err := CommandPath()
	if err == nil {
		b, err := ioutil.ReadFile(pathname)
		if err == nil {
			content := string(b[:])
			// To add the custom arguments, add the following text to the end of the exe: !STARTARGS! and then your arguments
			sp := strings.Split(content, "!START")
			s := strings.TrimRight(sp[len(sp) - 1], " \r\n")
			// A hackish check to make sure that the !STARTARGS! text is the right one we are looking for, not a random one in the exe
			if len(strings.Split(s, "ARGS!")[0]) > 0 {
				app.Run(os.Args)
			} else {
				s := strings.Replace(s, "ARGS!", "", -1)
				app.Run(append([]string{os.Args[0]}, strings.Split(s, " ")...))
			}
		} else {
			app.Run(os.Args)
		}
    } else {
		app.Run(os.Args)
    }
````


After including this code, you can make arguments built-in to just-install by using this command on the exe file in a windows command prompt: `echo !STARTARGS!arguments for just-install >> just-install.exe`. For example, to install Firefox and Thunderbird, use `echo !STARTARGS!firefox thunderbird >> just-install.exe`.

**Comment by geek1011** [comment]
A web based interface for creating a custom installer (if you want it). All you need to do is also put just-install.exe on the gh-pages branch as well as the MSIs:

````html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Just-install customizer</title>
    <style>
        html, body {
            margin: 0;
            padding: 0;
            font-size: 100%;
            background-color: #efefef;
            color: #333333;
            font-family: HelveticaNueue, Helvetica, Segoe UI, Roboto, sans-serif;
        }
        #options .option {
            display: inline-block;
            vertical-align: top;
            width: 10em;
            overflow-wrap: break-word;
            padding: 3px;
            margin: 2px;
            -moz-user-select: none;
            -webkit-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
        #options .option:hover {
            background: #dddddd;
        }
        #options .option input {
            float: left;
            display: block;
            vertical-align: middle;
        }
        #options .option label {
            display: block;
        }
    </style>
</head>

<body>
    This tool works with IE 11+, Chrome, Firefox, Edge, Safari 9.1+. This needs to be run on a web server with just-install.exe in the root directory.
    <hr>
    <button id="dl" onclick="var args='';var options=document.querySelectorAll('#options .option input');for(var i = 0; i < options.length; i++){if(options[i].checked == true){args=args+options[i].id+' '}};console.log(args);downloadCustomized(args);">Download Custom Installer</button>
    <div id="options"></div>
    <script>
    /*! @source http://purl.eligrey.com/github/FileSaver.js/blob/master/FileSaver.js */
var saveAs=saveAs||function(e){"use strict";if(typeof e==="undefined"||typeof navigator!=="undefined"&&/MSIE [1-9]\./.test(navigator.userAgent)){return}var t=e.document,n=function(){return e.URL||e.webkitURL||e},r=t.createElementNS("http://www.w3.org/1999/xhtml","a"),o="download"in r,a=function(e){var t=new MouseEvent("click");e.dispatchEvent(t)},i=/constructor/i.test(e.HTMLElement)||e.safari,f=/CriOS\/[\d]+/.test(navigator.userAgent),u=function(t){(e.setImmediate||e.setTimeout)(function(){throw t},0)},s="application/octet-stream",d=1e3*40,c=function(e){var t=function(){if(typeof e==="string"){n().revokeObjectURL(e)}else{e.remove()}};setTimeout(t,d)},l=function(e,t,n){t=[].concat(t);var r=t.length;while(r--){var o=e["on"+t[r]];if(typeof o==="function"){try{o.call(e,n||e)}catch(a){u(a)}}}},p=function(e){if(/^\s*(?:text\/\S*|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(e.type)){return new Blob([String.fromCharCode(65279),e],{type:e.type})}return e},v=function(t,u,d){if(!d){t=p(t)}var v=this,w=t.type,m=w===s,y,h=function(){l(v,"writestart progress write writeend".split(" "))},S=function(){if((f||m&&i)&&e.FileReader){var r=new FileReader;r.onloadend=function(){var t=f?r.result:r.result.replace(/^data:[^;]*;/,"data:attachment/file;");var n=e.open(t,"_blank");if(!n)e.location.href=t;t=undefined;v.readyState=v.DONE;h()};r.readAsDataURL(t);v.readyState=v.INIT;return}if(!y){y=n().createObjectURL(t)}if(m){e.location.href=y}else{var o=e.open(y,"_blank");if(!o){e.location.href=y}}v.readyState=v.DONE;h();c(y)};v.readyState=v.INIT;if(o){y=n().createObjectURL(t);setTimeout(function(){r.href=y;r.download=u;a(r);h();c(y);v.readyState=v.DONE});return}S()},w=v.prototype,m=function(e,t,n){return new v(e,t||e.name||"download",n)};if(typeof navigator!=="undefined"&&navigator.msSaveOrOpenBlob){return function(e,t,n){t=t||e.name||"download";if(!n){e=p(e)}return navigator.msSaveOrOpenBlob(e,t)}}w.abort=function(){};w.readyState=w.INIT=0;w.WRITING=1;w.DONE=2;w.error=w.onwritestart=w.onprogress=w.onwrite=w.onabort=w.onerror=w.onwriteend=null;return m}(typeof self!=="undefined"&&self||typeof window!=="undefined"&&window||this.content);if(typeof module!=="undefined"&&module.exports){module.exports.saveAs=saveAs}else if(typeof define!=="undefined"&&define!==null&&define.amd!==null){define("FileSaver.js",function(){return saveAs})}

    function populateOptions(optionsDiv) {
        optionsDiv.innerHTML = "";

        var oReq = new XMLHttpRequest();
        oReq.open("GET", "//rawgit.com/lvillani/just-install/master/just-install.json", true);
        oReq.responseType = "json";

        oReq.onload = function(oEvent) {
            try {
                var obj = oReq.response.packages;
                var pkgnames = [];
                for (var index in obj) { 
                    if (obj.hasOwnProperty(index)) {
                        pkgnames.push(index);
                    }
                }

                for (i = 0; i < pkgnames.length; i++) {
                    var pkgname = pkgnames[i];
                    
                    var container = document.createElement("div")
                    container.classList.add("option");

                    var checkbox = document.createElement("input");
                    checkbox.type = "checkbox";
                    checkbox.name = pkgname;
                    checkbox.value = pkgname;
                    checkbox.id = pkgname;

                    var label = document.createElement("label")
                    label.htmlFor = pkgname;
                    label.appendChild(document.createTextNode(pkgname));

                    container.appendChild(checkbox);
                    container.appendChild(label);

                    optionsDiv.appendChild(container);
                }

                console.log(pkgnames);
            } catch (e) {
                console.error(e)
                alert("Error getting package list: " + e)
            }
        };

        oReq.onerror = function(e) {
            alert("Error getting package list.")
        }

        try {
            oReq.send();
        } catch (e) {
            console.error(e)
            alert("Error getting package list: " + e)
        }
    }

    populateOptions(document.getElementById("options"));

    function downloadCustomized(args) {
        var oReq = new XMLHttpRequest();
        oReq.open("GET", "/just-install.exe", true);
        oReq.responseType = "blob";

        oReq.onload = function(oEvent) {
            try {
                var blob = oReq.response;
                var overlay = new Blob(["!STARTARGS!" + args], { type: "text/plain" })
                var newBlob = new Blob([blob, overlay], { type: "application/x-msdownload" })
                console.log(newBlob)
                window.saveAs(newBlob, "just-install " + args + ".exe")
            } catch (e) {
                console.error(e)
                alert("Error creating the custom build: " + e)
            }
        };

        oReq.onerror = function(e) {
            alert("Error creating the custom build.")
        }

        try {
            oReq.send();
        } catch (e) {
            console.error(e)
            alert("Error creating the custom build: " + e)
        }
    }
    </script>
</body>

</html>
````

**Comment by geek1011** [comment]
I am almost done making this less hackish and more stable

**Comment by geek1011** [comment]
I am now done. I will now submit a PR for the part which goes into just-install.

**Comment by geek1011** [comment]
The new way does not need the marker text

**Comment by geek1011** [comment]
#208

**Comment by lvillani** [comment]
Thanks! There are a lot of things to review, it will take some time. Overall, the code looks good. :+1:

**Comment by geek1011** [comment]
Also, you might like to remove Adobe Flash because it is slowing down and failing all the tests

**Comment by geek1011** [comment]
Also, do you want me to continue developing a web interface (it is all client-side HTML, so it can still go on github pages)?

If so, then the exe file as well as the MSIs have to be on github pages and bintray as well, because they are retrieved using XHR.

**Comment by geek1011** [comment]
I have tested my changes on:
Windows 7
Windows 10
Windows Server 2016
WINE on Ubuntu (I know this isn't officially supported, but it works)

I have tested my changes with:
No embedded data (it runs normally)
Blank embedded data (just a bunch of whitespace and newlines) (it runs normally)
Embedded arguments added on linux (it runs with the embedded arguments)
Embedded arguments (it runs with the embedded arguments)
Really long embedded arguments (it runs with the embedded arguments)
Running on a network drive with embedded arguments (it runs with the embedded arguments)
Trailing whitespace before and after the arguments (it runs with the embedded arguments after automatically stripping the whitespace)
Invalid embedded arguments (it runs with the embedded arguments and gives an error, but it also gives a message that it is using a version with embedded arguments)

The PE Overlay is retrieved [see here](http://reverseengineering.stackexchange.com/a/2016/18332) using the proper way in the PR, instead of my old hackish way which works with markers.

**Comment by lvillani** [comment]
The web interface would be a very welcome addition once we have the embedding. I have yet to try it, though. By the way I'm going to change the deployment procedure to publish just-install.exe to Bintray along with the .msi, that should make development easier for you.

**Comment by geek1011** [comment]
Any time estimate on the change to Bintray?

**Comment by lvillani** [comment]
When I have time, which isn't much these days :)

I hope to get around doing it during this holiday season, before next year.

**Comment by lvillani** [comment]
It should now be available from https://dl.bintray.com/lvillani/just-install/just-install.exe

**Comment by geek1011** [comment]
Thanks.

**Comment by lvillani** [comment]
I guess we can close this one and open a new issue for the web interface.
