### ISSUE TITLE
Argument for update-url

### ISSUE THREAD

**Issue by ingob1** [lvillani/just-install#214]
It would be nice to be able to install and/or configure just-install with an argument specifying the update url (where just-install.json can be fetched). That way it would be possible to always use your own registry file with the software you want. Especially concerning different languages that would be helpful. Or is that already possible?

**Comment by geek1011** [comment]
At the moment, there is no argument, but if there is a `just-install.json` in the same folder as `just-install.exe`, it will use it. See https://github.com/lvillani/just-install/blob/master/registry.go#L115

**Comment by geek1011** [comment]
A workaround is you could do a custom build with [this](https://github.com/lvillani/just-install/blob/master/registry.go#L20) line changed to your own registry URL.

**Comment by ingob1** [comment]
Great, thanks for the information, placing the json in the same directory will do the job.

**Comment by geek1011** [comment]
@ingob1 You're welcome. If you want, and @lvillani agrees, I could start working on a feature to load it from a custom URL.

**Comment by lvillani** [comment]
In #210 there's a checklist item that explicitly states that custom registry URLs won't be supported. The reasoning is that #208 allows people to inject arbitrary arguments to just-install's CLI arguments list, which means that it would be possible for people to start distributing executables based on just-install that can be used as a vehicle to install malware. The last thing we want to do is to have AV software flag `just-install.exe` as a threat.

I'm closing this issue for now, to signal that we are not (and we should not work) on this at the moment. 

Let's focus on #207, #209, #210, and #212, then let's revisit this one later.

**Comment by geek1011** [comment]
Ok. I understand your reasoning.
