### ISSUE TITLE
Export packages from Npackd repositories

### ISSUE THREAD

**Issue by tim-lebedkov** [lvillani/just-install#72]
Hi,

now that just-install has advanced, have you considered exporting packages from an existing Npackd repository like this one?

http://npackd.appspot.com/rep/xml?tag=stable

**Comment by lvillani** [comment]
You mean converting Npackd repositories in a format compatible with just-install's "registry"?

**Comment by tim-lebedkov** [comment]
yes

**Comment by lvillani** [comment]
That's certainly a possibility but I would wait until I release just-install 3.0 (which breaks compatibility of the registry format and formalises its structure with JSON-schema).

I'm waiting to sort out some issues I have with Windows installer before pushing it as a stable release (since I'm using it already).

**Comment by tim-lebedkov** [comment]
I saw that branch. If you plan to import packages from Npackd, it would be nice to make the packages more compatible with Npackd as you break the compatibility with Just Install 2.0 anyway.

**Comment by lvillani** [comment]
I'm open to import packages from Npackd but I'm very strict about anything that adds complexity to the project. (Adding JSON schema was a necessary evil to clean up the registry format and make it more consistent, formal, and testable by a machine, in addition to act as documentation).

Did you have something specific in mind?

**Comment by tim-lebedkov** [comment]
.msi and .zip packages can be supported very easily, but many other packages require dependencies for the installation and complicated scripts. That's why I would suggest that the converter program contains a table of Npackd package names and corresponding Just Install package types like this one:

Npackd package name | Just Install package type
------------------------------|----------------------------------
com.softwareok.QDir | zip
io.github.hexchat | innosetup

Only the packages listed in this table will be converted. This way **no changes in the Just Install registry format are necessary**.

Nonetheless I would recommend to add support for longer .bat installation scripts. One command is not always enough.

**Comment by lvillani** [comment]
There are no plans to write a conversion script for the time being. Of course, I'm open to the possibility but I don't have the time to do it myself. I'm closing this ticket for now. Will re-open if necessary in the future.
