### ISSUE TITLE
Put a landing page on just-install.it

### ISSUE THREAD

**Issue by naufraghi** [lvillani/just-install#74]
With a big
```
  msiexec.exe /i http://go.just-install.it
```
and a link to github for example.

**Comment by lvillani** [comment]
:+1:

**Comment by lvillani** [comment]
Aaaaand done!

**Comment by naufraghi** [comment]
😊👌

Il giorno 14:26 mer 13/mag/2015 Lorenzo Villani <notifications@github.com>
ha scritto:
