### ISSUE TITLE
Backslashes are not all escaped in registry file

### ISSUE THREAD

**Issue by aurelien-rainone** [lvillani/just-install#88]
My installation script using **just-install** (really great tool btw :+1: ) is quitting unexpectedly.

Having a look at the registry, I saw that some backslashes in the `"options/shims"` field for *ruby* and *subversion* for example, were not escaped. Don't know if it only happens there
```json
    "ruby": {
      "version": "1.9.3-p545",
      "installer": {
        "kind": "innosetup",
        "x86": "http://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-{{.version}}.exe?direct",
        "options": {
          "shims": [
            "{{.SYSTEMDRIVE}}\\Ruby193\bin\ruby.exe",
            "{{.SYSTEMDRIVE}}\\Ruby193\bin\rubyw.exe"
          ]
        }
      }
    },
```

**Comment by lvillani** [comment]
Should be working now, can you give it a try?

**Comment by aurelien-rainone** [comment]
I'll give a try tomorrow morning and let you know
Thanks

**Comment by aurelien-rainone** [comment]
Yep it's working!
