### ISSUE TITLE
Why do we need an MSI to install Just-Install?

### ISSUE THREAD

**Issue by michaelsync** [lvillani/just-install#91]
Hello,

I've read your post about how you started creating Just-install. I like it. 

But when I run this command "msiexec.exe /i http://go.just-install.it", it show the MSI screen because http://go.just-install.it has just-install.msi. I agreed with you that we won't be able to remember the chocolatey's command. but using just-install.msi is a bit weird. Is there any way to improve it? How do we do silent-install "just-install" on windows box?

**Comment by lvillani** [comment]
Run `msiexec.exe /q /i http://go.just-install.it` (notice the `/q` switch).

`msiexec` is the only memorable way to fetch a file from the internet and install it across all versions of Windows since it has a built-in HTTP client.
